#mysql相关
mysql:
    infor: 代理202.1
    host: 192.168.51.126
    port: 1031
    user: root
    pwd: mypassword
    dbname: joytest


mysql1:
    infor: 直连202.1
    host: 192.168.202.1
    port: 3306
    user: root
    pwd: mypassword
    dbname: joytest


